{
 "title": "PharmaGo - Business",
 "tags": [
  "pharmago",
  "business"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Eventos de negocio por tipo",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 16, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "round(sum by (event, outcome) (increase(pharmago_business_events_total[1m])))",
     "legendFormat": "{{event}} {{outcome}}"
    }
   ]
  },
  {
   "title": "Eventos de negocio fallidos",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(sum(increase(pharmago_business_events_total{outcome=\"failed\"}[$__range])))"
    }
   ]
  },
  {
   "title": "Compras creadas total",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(pharmago_purchases_created_total)"
    }
   ]
  },
  {
   "title": "Monto acumulado de compras",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(pharmago_purchase_amount_total_UYU)"
    }
   ]
  },
  {
   "title": "Total de items comprados",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(pharmago_purchase_items_total)"
    }
   ]
  },
  {
   "title": "Intentos de login por resultado",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "round(sum by (outcome) (increase(pharmago_login_attempts_total[2m])))",
     "legendFormat": "login {{outcome}}"
    }
   ]
  },
  {
   "title": "Compras realizadas",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "round(sum(increase(pharmago_purchases_created_total[1m])))",
     "legendFormat": "compras realizadas"
    }
   ]
  },
  {
   "title": "Cambios de estado de compra",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "round(sum by (status) (increase(pharmago_purchase_status_changes_total[1m])))",
     "legendFormat": "{{status}}"
    }
   ]
  }
 ]
}