{
 "title": "PharmaGo - SLIs SLOs",
 "tags": [
  "pharmago",
  "slo"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Availability objetivo 99.9%",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(1 - (sum(rate(pharmago_http_errors_total_1[5m])) / sum(rate(pharmago_http_requests_total_1[5m])))) * 100"
    }
   ]
  },
  {
   "title": "Latency P95 objetivo < 500ms",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by (le) (rate(pharmago_http_request_duration_milliseconds_ms_bucket[5m])))"
    }
   ]
  },
  {
   "title": "Error Rate objetivo < 1%",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(pharmago_http_errors_total_1[5m])) / sum(rate(pharmago_http_requests_total_1[5m])) * 100"
    }
   ]
  },
  {
   "title": "Throughput",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(pharmago_http_requests_total_1[5m]))"
    }
   ]
  }
 ]
}